# Generated by Django 3.0.8 on 2020-07-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary_main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.AddField(
            model_name='about_me',
            name='git',
            field=models.CharField(default='None', max_length=100, null=True, verbose_name='Github'),
        ),
    ]
