# Generated by Django 3.0.8 on 2020-07-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary_main', '0002_auto_20200725_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_me',
            name='email',
            field=models.CharField(default='None', max_length=100, null=True, verbose_name='Github'),
        ),
        migrations.AddField(
            model_name='about_me',
            name='linkedin',
            field=models.CharField(default='None', max_length=100, null=True, verbose_name='Github'),
        ),
        migrations.AddField(
            model_name='about_me',
            name='telegram',
            field=models.CharField(default='None', max_length=100, null=True, verbose_name='Github'),
        ),
        migrations.AddField(
            model_name='about_me',
            name='twitter',
            field=models.CharField(default='None', max_length=100, null=True, verbose_name='Github'),
        ),
    ]
