# Generated by Django 3.0.8 on 2020-08-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary_main', '0003_auto_20200725_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_me',
            name='email',
            field=models.CharField(default='None', max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='about_me',
            name='linkedin',
            field=models.CharField(default='None', max_length=100, null=True, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='about_me',
            name='telegram',
            field=models.CharField(default='None', max_length=100, null=True, verbose_name='telegram'),
        ),
        migrations.AlterField(
            model_name='about_me',
            name='twitter',
            field=models.CharField(default='None', max_length=100, null=True, verbose_name='twitter'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='title',
            field=models.CharField(default='example name experiences', max_length=100, verbose_name='Название'),
        ),
    ]
