# Generated by Django 3.0.8 on 2020-08-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary_main', '0004_auto_20200803_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiences',
            name='post_time',
        ),
    ]
