# Generated by Django 3.0.8 on 2020-08-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary_main', '0005_remove_experiences_post_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carer_profile',
        ),
    ]
